#ifndef ROMESOCKET_ERROR_H_
#define ROMESOCKET_ERROR_H_

enum class ERROR_CODE : int
{
    SUCCESS = 1,
    UNKNOWN_IP_VERSION = 0,
    UNKNOWN_SOCKET_TYPE = -1,
    OVERFLOW = -2,
    CONNECTION_CLOSED_BY_PEER = -3,
    UNKNOWN_ERROR = -4,
    FAILURE_CREATING_SOCKET = -5,
    FAILURE_BINDING_PORT = -6,
    FAILURE_LISTENING_PORT = -7,
    SOCKET_ALREADY_EXISTS = -8,
    INVALID_SOCKET = -9,
    FAILURE_ACCEPT_CLIENT = -10
};

#endif